import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import GradientFollower from "./components/GradientFollower";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jacob Stevenson",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GradientFollower>
          <main>{children}</main>
        </GradientFollower>
      </body>
    </html>
  );
}
